// Minimal native flat config compatible with ESLint v10.
//
// History: this used to extend `eslint-config-next` via `FlatCompat.extends()`,
// which broke in two stages:
//   1. `@eslint/eslintrc`'s config validator JSON.stringifies the loaded
//      plugins to format errors, and chokes on the circular references inside
//      `eslint-plugin-react`. Bypassed by importing the flat config directly.
//   2. `eslint-config-next@16` bundles `eslint-plugin-react@7.37` which uses
//      `context.getFilename()` — removed in ESLint v9. Loading it crashes
//      every lint run with `contextOrFilename.getFilename is not a function`.
//
// Until `eslint-plugin-react` ships a release compatible with ESLint v10+
// (tracked at jsx-eslint/eslint-plugin-react#3697), we use a minimal config
// that enables only the rules that actually work on this ESLint version:
//   - `@typescript-eslint` (works with v10)
//   - `@next/eslint-plugin-next` (works with v10)
//   - our custom `no-silent-catch` rule
//
// Lost coverage: the React-specific rules (JSX a11y, react-hooks/exhaustive-deps,
// react/no-unknown-property, etc.). These should be re-enabled the moment
// upstream catches up — search this file for "TODO(eslint-plugin-react)".
import tseslint from "typescript-eslint";
import nextPlugin from "@next/eslint-plugin-next";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import noSilentCatchPlugin from "./eslint-rules/no-silent-catch.mjs";

const eslintConfig = [
  // Apply TypeScript ESLint to .ts/.tsx files only.
  ...tseslint.configs.recommended.map((cfg) => ({
    ...cfg,
    files: ["**/*.{ts,tsx,mts,cts}"],
  })),
  {
    files: ["**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}"],
    plugins: {
      "@next/next": nextPlugin,
      "react-hooks": reactHooksPlugin,
      "jsx-a11y": jsxA11yPlugin,
      local: noSilentCatchPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
      ...reactHooksPlugin.configs.recommended.rules,
      // The v7 strict rules (set-state-in-effect, refs, immutability,
      // preserve-manual-memoization, purity) are NEW in eslint-plugin-react-hooks
      // v7 and the legacy code predates them — downgrade to `warn` and clean
      // up file-by-file as touched. The classic rules-of-hooks and
      // exhaustive-deps stay as `error` (they catch real bugs).
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/purity": "warn",
      // jsx-a11y: only the rules that fire on raw HTML elements, not the
      // ones that need eslint-plugin-react's JSX context analysis.
      "jsx-a11y/click-events-have-key-events": "warn",
      "jsx-a11y/no-static-element-interactions": "warn",
      // CLAUDE.md: never swallow errors silently. Every catch block must
      // log/rethrow/report — no quietly mutating state and moving on.
      //
      // Currently `warn` not `error` because the legacy codebase has ~108
      // pre-existing violations (the lint pipeline was broken for a while —
      // `next lint` was removed in Next.js 16). Fix file-by-file as we touch
      // them (same pattern as backend `no-floating-promises`), then flip to
      // `error` once the count hits zero. New code should not add violations.
      "local/no-silent-catch": "warn",
      // `catch {}` and `catch (e) {}` are still hard errors — egregious form.
      "no-empty": ["error", { allowEmptyCatch: false }],
      // Match the backend's policy: unused vars warn but don't fail. Allow
      // `_` prefix for intentionally-unused params (e.g. exhaustiveness checks).
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          args: "none",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // TODO(eslint-plugin-react): re-enable React/JSX rules once
      // eslint-plugin-react supports ESLint v10 (jsx-eslint/eslint-plugin-react#3697).
    },
  },
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // The custom rule file is a plugin entry point — exclude from linting.
      "eslint-rules/**",
      // OpenAPI codegen output — regenerated by `npm run openapi:gen`. The
      // file already disables ESLint at the top; ignoring at the config
      // layer is cleaner and means we don't lint code we don't author.
      "src/lib/generated/**",
    ],
  },
];

export default eslintConfig;
